### PR TITLE
Add contrib.pretty submodule to add pretty-formatting in IPython

### PR DESCRIPTION
**Pull request by harrymander**
Usage:

```python
from dataclasses_struct.contrib.ipython import init_pretty_repr

init_pretty_repr()

import dataclasses_struct as dcs
# ...
```

Then instances of any class decorated with `@dcs.dataclass()` will have a `_repr_pretty_` method that causes it to be formatted with indentation and color (if rich is installed) when displayed in the IPython shell and in Jupyter notebooks.

### CODE REVIEW

**Comment by harrymander** [comment]
See example here: https://gist.github.com/harrymander/5df6d287b00233c42a4a4cda3361e566

**Comment by coldino** [comment]
Nice, that's a good way to handle it for efficiency.

**Comment by coldino** [comment]
One issue with this approach is with requiring an import order like this. In a bigger project where you might import this library into multiple files it is going to be annoying to ensure this patch is applied first.

For instance in my case I'm going to need to add this patching step in my `main` module, which in my view should not have this sort of involvement with libraries that submodules are using.

**Comment by coldino** [comment]
Probably also need to guard against multiple calls to `init_pretty_repr`.

**Comment by harrymander** [comment]
Yes agree that that approach is not ideal. However, I'm trying to keep things as close as possible to standard dataclasses, which are supposed to be fairly basic.

Note other libraries which offer dataclass-like classes like `pydantic` and `attrs` don't built-in pretty reprs. E.g. pydantic tells you to use `rich`: https://docs.pydantic.dev/latest/integrations/rich/, which already natively supports dataclasses.

I discovered you can use `%load_ext rich` in IPython or notebooks to wrap all objects' repr in `rich.print`. See example here: https://gist.github.com/harrymander/f9f1b03779b55c9d649bbed89c8de87b

**Comment by coldino** [comment]
I had not heard of Rich, and although it seems interesting it is a shame to need yet another dependancy to do something IPython already does and only takes a single method to support.

One thing I'm missing from these other options that IPython pprint gave me was an easy way to output all ints as hex globally. Really invaluable for all machine-level work.

I guess I'll have to do some monkey patching of my own despite your solution.

**Pull request closed without merging**
